let records = [
	{ 'artist': '10,000 Maniacs', 'title': 'In My Tribe', 'releaseDate': 1987, 'coverArt': '10,000_Maniacs-In_My_Tribe.jpg' },
	{ 'artist': 'Aerosmith', 'title': 'Draw the Line', 'releaseDate': 1977, 'coverArt': 'Aerosmith-Draw_the_Line.jpg' },
	{ 'artist': 'Al Stewart', 'title': 'Year of the Cat', 'releaseDate': 1976, 'coverArt': 'Al_Stewart-Year_of_the_Cat.jpg' },
	{ 'artist': 'Allman Brothers Band', 'title': 'Eat a Peach', 'releaseDate': 1972, 'coverArt': 'Allman_Brothers_Band-Eat_a_Peach.jpg' },
	{ 'artist': 'Amy Winehouse', 'title': 'Back to Black', 'releaseDate': 2006, 'coverArt': 'Amy_Winehouse-Back_to_Black.jpg' },	
	{ 'artist': 'Bad Company', 'title': 'Bad Company', 'releaseDate': 1974, 'coverArt': 'Bad_Company-Bad_Company.jpg' },
	{ 'artist': 'Be Bop Deluxe', 'title': 'Axe Victim', 'releaseDate': 1974, 'coverArt': 'Be_Bop_Deluxe-Axe_Victim.jpg' },
	{ 'artist': 'Beach Boys', 'title': 'Pet Sounds', 'releaseDate': 1966, 'coverArt': 'Beach_Boys-Pet_Sounds.jpg' },
	{ 'artist': 'Beach Boys', 'title': 'Spirit of America', 'releaseDate': 1975, 'coverArt': 'Beach_Boys-Spirit_of_America.jpg' },
	{ 'artist': 'Beatles', 'title': 'Abbey Road', 'releaseDate': 1969, 'coverArt': 'Beatles-Abbey_Road.jpg' },
	{ 'artist': 'Beatles', 'title': 'Sgt. Pepper\'s Lonely Heart Club Band', 'releaseDate': 1967, 'coverArt': 'Beatles-Sgt._Peppers_Lonely_Heart_Club_Band.jpg' },
	{ 'artist': 'Beatles', 'title': 'Revolver', 'releaseDate': 1966, 'coverArt': 'Beatles-Revolver.jpg' },
	{ 'artist': 'Blondie', 'title': 'Parallel Lines', 'releaseDate': 1978, 'coverArt': 'Blondie-Parallel_Lines.jpg' },
	{ 'artist': 'Boston', 'title': 'Boston', 'releaseDate': 1976, 'coverArt': 'Boston-Boston.jpg' },
	{ 'artist': 'Bruce Springsteen', 'title': 'Born in the USA', 'releaseDate': 1984, 'coverArt': 'Bruce_Springsteen-Born_in_the_USA.jpg' },	
	{ 'artist': 'Bruce Springsteen', 'title': 'Born to Run', 'releaseDate': 1975, 'coverArt': 'Bruce_Springsteen-Born_to_Run.jpg' },
	{ 'artist': 'Bruce Springsteen', 'title': 'Greetings From Asbury Park NJ', 'releaseDate': 1973, 'coverArt': 'Bruce_Springsteen-Greetings_From_Asbury_Park_NJ.jpg' },
	{ 'artist': 'Carole King', 'title': 'Tapestry', 'releaseDate': 1971, 'coverArt': 'Carole_King-Tapestry.jpg' },
	{ 'artist': 'Cars', 'title': 'Candy-O', 'releaseDate': 1979, 'coverArt': 'Cars-Candy-O.jpg' },
	{ 'artist': 'Cat Stevens', 'title': 'Tea for the Tillerman', 'releaseDate': 1971, 'coverArt': 'Cat_Stevens-Tea_for_the_Tillerman.jpg' },
	{ 'artist': 'Chicago', 'title': 'X', 'releaseDate': 1980, 'coverArt': 'Chicago-X.jpg' },
	{ 'artist': 'Cream', 'title': 'Disraeli Gears', 'releaseDate': 1968, 'coverArt': 'Cream-Disraeli_Gears.jpg' },
	{ 'artist': 'Cyndi Lauper', 'title': 'She\'s So Unusual', 'releaseDate': 1983, 'coverArt': 'Cyndi_Lauper-Shes_So_Unusual.jpg' },
	{ 'artist': 'David Bowie', 'title': 'Aladdin Sane', 'releaseDate': 1973, 'coverArt': 'David_Bowie-Aladdin_Sane.jpg' },	
	{ 'artist': 'David Bowie', 'title': 'Diamond Dogs', 'releaseDate': 1974, 'coverArt': 'David_Bowie-Diamond_Dogs.jpg' },
	{ 'artist': 'Deep Purple', 'title': 'Burn', 'releaseDate': 1974, 'coverArt': 'Deep_Purple-Burn.jpg' },	
	{ 'artist': 'Deep Purple', 'title': 'In Rock', 'releaseDate': 1970, 'coverArt': 'Deep_Purple-In_Rock.jpg' },	
	{ 'artist': 'Derek & the Dominos', 'title': 'Layla', 'releaseDate': 1970, 'coverArt': 'Derek_&_Dominos-Layla.jpg' },	
	{ 'artist': 'Devo', 'title': 'Q: Are We Not Men?', 'releaseDate': 1978, 'coverArt': 'Devo-Q_Are_We_Not_Men.jpg' },	
	{ 'artist': 'Doors', 'title': 'Strange Days', 'releaseDate': 1967, 'coverArt': 'Doors-Strange_Days.jpg' },	
	{ 'artist': 'Eagles', 'title': 'Hotel California', 'releaseDate': 1976, 'coverArt': 'Eagles-Hotel_California.jpg' },	
	{ 'artist': 'Electric Light Orchestra', 'title': 'Out of the Blue', 'releaseDate': 1977, 'coverArt': 'Electric_Light_Orchestra-Out_of_the_Blue.jpg' },	
	{ 'artist': 'Elton John', 'title': 'Captain Fantastic', 'releaseDate': 1975, 'coverArt': 'Elton_John-Captain_Fantastic.jpg' },	
	{ 'artist': 'Elvis Costello', 'title': 'My Aim Is True', 'releaseDate': 1977, 'coverArt': 'Elvis_Costello-My_Aim_Is_True.jpg' },	
	{ 'artist': 'Elvis Presley', 'title': 'Elvis Presley', 'releaseDate': 1956, 'coverArt': 'Elvis_Presley-Elvis_Presley.jpeg' },	
	{ 'artist': 'Fleetwood Mac', 'title': 'Rumours', 'releaseDate': 1977, 'coverArt': 'Fleetwood_Mac-Rumours.jpg' },	
	{ 'artist': 'Foghat', 'title': 'Rock & Roll', 'releaseDate': 1973, 'coverArt': 'Foghat-Rock_&_Roll.jpg' },	
	{ 'artist': 'Frank Zappa', 'title': 'Cruising with Ruben & the Jets', 'releaseDate': 1968, 'coverArt': 'Frank_Zappa-Cruising_with_Ruben_&_the_Jets.jpg' },	
	{ 'artist': 'Frank Zappa', 'title': 'Weasels Ripped My Flesh', 'releaseDate': 1970, 'coverArt': 'Frank_Zappa-Weasels_Ripped_My_Flesh.jpg' },	
	{ 'artist': 'Funkadelic', 'title': 'Maggot Brain', 'releaseDate': 1971, 'coverArt': 'Funkadelic-Maggot_Brain.jpg' },	
	{ 'artist': 'Go-Go\'s', 'title': 'Vacation', 'releaseDate': 1982, 'coverArt': 'Go-Gos-Vacation.jpg' },
	{ 'artist': 'Go-Go\'s', 'title': 'Beauty & the Beat', 'releaseDate': 1981, 'coverArt': 'Go-Gos-Beauty_and_the_Beat.jpg' },	
	{ 'artist': 'Goo Goo Dolls', 'title': 'A Boy Named Goo', 'releaseDate': 1995, 'coverArt': 'Goo_Goo_Dolls-A_Boy_Named_Goo.jpg' },
	{ 'artist': 'Graham Parker', 'title': 'The Parkerilla', 'releaseDate': 1978, 'coverArt': 'Graham_Parker-The_Parkerilla.jpg' },	
	{ 'artist': 'Grand Funk', 'title': 'E Pluribus Funk', 'releaseDate': 1971, 'coverArt': 'Grand_Funk-E_Pluribus_Funk.jpg' },	
	{ 'artist': 'Green Day', 'title': 'Dookie', 'releaseDate': 1994, 'coverArt': 'Green_Day-Dookie.jpg' },	
	{ 'artist': 'Jethro Tull', 'title': 'Aqualung', 'releaseDate': 1971, 'coverArt': 'Jethro_Tull-Aqualung.jpg' },	
	{ 'artist': 'Jimi Hendrix', 'title': 'Are You Experienced', 'releaseDate': 1967, 'coverArt': 'Jimi_Hendrix-Are_You_Experienced.jpg' },	
	{ 'artist': 'Joan Jett', 'title': 'Album', 'releaseDate': 1983, 'coverArt': 'Joan_Jett-Album.jpg' },	
	{ 'artist': 'Joe Jackson', 'title': 'Look Sharp', 'releaseDate': 1979, 'coverArt': 'Joe_Jackson-Look_Sharp.jpg' },	
	{ 'artist': 'Joy Division', 'title': 'Unknown Pleasures', 'releaseDate': 1979, 'coverArt': 'Joy_Division-Unknown_Pleasures.jpg' },		
	{ 'artist': 'King Crimson', 'title': 'In the Court of the Crimson King', 'releaseDate': 1969, 'coverArt': 'King_Crimson-In_the_Court_of_the_Crimson_King.jpg' },	
	{ 'artist': 'Kurt Baker Combo', 'title': 'In Orbit', 'releaseDate': 2016, 'coverArt': 'Kurt_Baker_Combo-In_Orbit.jpg' },	
	{ 'artist': 'Led Zeppelin', 'title': 'Led Zeppelin', 'releaseDate': 1969, 'coverArt': 'Led_Zeppelin-I.jpg' },	
	{ 'artist': 'Led Zeppelin', 'title': 'Presence', 'releaseDate': 1976, 'coverArt': 'Led_Zeppelin-Presence.jpg' },	
	{ 'artist': 'Little Feat', 'title': 'Sailin\' Shoes', 'releaseDate': 1972, 'coverArt': 'Little_Feat-Sailin_Shoes.jpg' },	
	{ 'artist': 'New York Dolls', 'title': 'New York Dolls', 'releaseDate': 1973, 'coverArt': 'New_York_Dolls-New_York_Dolls.jpg' },	
	{ 'artist': 'Nirvana', 'title': 'Nevermind', 'releaseDate': 1991, 'coverArt': 'Nirvana-Nevermind.jpg' },	
	{ 'artist': 'Nuclear Valdez', 'title': 'I Am I', 'releaseDate': 1989, 'coverArt': 'Nuclear_Valdez-I_Am_I.jpg' },	
	{ 'artist': 'Ozzy Osbourne', 'title': 'Bark at the Moon', 'releaseDate': 1983, 'coverArt': 'Ozzy_Osbourne-Bark_at_the_Moon.jpg' },	
	{ 'artist': 'Patti Smith', 'title': 'Horses', 'releaseDate': 1975, 'coverArt': 'Patti_Smith-Horses.jpg' },	
	{ 'artist': 'Paul & Linda McCartney', 'title': 'Ram', 'releaseDate': 1971, 'coverArt': 'Paul_McCartney-Ram.jpg' },	
	{ 'artist': 'Peter Gabriel', 'title': 'Peter Gabriel (Melt)', 'releaseDate': 1980, 'coverArt': 'Peter_Gabriel-Melt.jpg' },	
	{ 'artist': 'Pink Floyd', 'title': 'Dark Side of the Moon', 'releaseDate': 1973, 'coverArt': 'Pink_Floyd-Dark_Side_of_the_Moon.jpg' },	
	{ 'artist': 'Pink Floyd', 'title': 'Wish You Were Here', 'releaseDate': 1975, 'coverArt': 'Pink_Floyd-Wish_You_Were_Here.jpg' },	
	{ 'artist': 'Queen', 'title': 'Queen II', 'releaseDate': 1974, 'coverArt': 'Queen-Queen_II.jpg' },	
	{ 'artist': 'REM', 'title': 'Chronic_Town', 'releaseDate': 1982, 'coverArt': 'REM-Chronic_Town.jpg' },	
	{ 'artist': 'Ramones', 'title': 'Ramones', 'releaseDate': 1976, 'coverArt': 'Ramones-Ramones.jpg' },	
	{ 'artist': 'Rick Springfield', 'title': 'Working Class Dog', 'releaseDate': 1981, 'coverArt': 'Rick_Springfield-Working_Class_Dog.jpg' },	
	{ 'artist': 'Rolling Stones', 'title': 'Let It Bleed', 'releaseDate': 1969, 'coverArt': 'Rolling_Stones-Let_It_Bleed.jpg' },	
	{ 'artist': 'Rolling Stones', 'title': 'Some Girls', 'releaseDate': 1978, 'coverArt': 'Rolling_Stones-Some_Girls.jpg' },	
	{ 'artist': 'Rolling Stones', 'title': 'Sticky Fingers', 'releaseDate': 1971, 'coverArt': 'Rolling_Stones-Sticky_Fingers.jpg' },	
	{ 'artist': 'Roxy Music', 'title': 'Siren', 'releaseDate': 1975, 'coverArt': 'Roxy_Music-Siren.jpg' },	
	{ 'artist': 'Rush', 'title': 'Moving Pictures', 'releaseDate': 1981, 'coverArt': 'Rush-Moving_Pictures.jpg' },	
	{ 'artist': 'Savoy Brown', 'title': 'Looking In', 'releaseDate': 1970, 'coverArt': 'Savoy_Brown-Looking_In.jpg' },		
	{ 'artist': 'Sex Pistols', 'title': 'Never Mind the Bollocks, Here\'s the Sex Pistols', 'releaseDate': 1977, 'coverArt': 'Sex_Pistols-Never_Mind_the_Bollocks.jpg' },	
	{ 'artist': 'Small Faces', 'title': 'Ogden\'s Nut Gone Flake', 'releaseDate': 1968, 'coverArt': 'Small_Faces-Ogdens_Nut_Gone_Flake.jpg' },	
	{ 'artist': 'Smashing Pumpkins', 'title': 'Mellon Collie & the Infinite Sadness', 'releaseDate': 1995, 'coverArt': 'Smashing_Pumpkins-Mellon_Collie_&_Infinite_Sadness.jpg' },	
	{ 'artist': 'Social Distortion', 'title': 'Social Distortion', 'releaseDate': 1990, 'coverArt': 'Social_Distortion-Social_Distortion.jpg' },	
	{ 'artist': 'Sonic Youth', 'title': 'Dirty', 'releaseDate': 1992, 'coverArt': 'Sonic_Youth-Dirty.jpg' },	
	{ 'artist': 'Sparks', 'title': 'Kimono My House', 'releaseDate': 1974, 'coverArt': 'Sparks-Kimono_My_House.jpg' },	
	{ 'artist': 'Squeeze', 'title': 'Cool for Cats', 'releaseDate': 1979, 'coverArt': 'Squeeze-Cool_For_Cats.jpg' },	
	{ 'artist': 'Steve Miller Band', 'title': 'The Joker', 'releaseDate': 1973, 'coverArt': 'Steve_Miller_Band-The_Joker.jpg' },	
	{ 'artist': 'Supertramp', 'title': 'Breakfast in America', 'releaseDate': 1979, 'coverArt': 'Supertramp-Breakfast_in_America.jpg' },	
	{ 'artist': 'T. Rex', 'title': 'The Slider', 'releaseDate': 1972, 'coverArt': 'T_Rex-Slider.jpg' },	
	{ 'artist': 'The Clash', 'title': 'London Calling', 'releaseDate': 1979, 'coverArt': 'The_Clash-London_Calling.jpg' },	
	{ 'artist': 'The Like', 'title': 'Release Me', 'releaseDate': 2010, 'coverArt': 'The_Like-Release_Me.jpg' },	
	{ 'artist': 'The Who', 'title': 'The Who By Numbers', 'releaseDate': 1975, 'coverArt': 'The_Who-By_Numbers.jpg' },	
	{ 'artist': 'The Who', 'title': 'The Who Sell Out', 'releaseDate': 1967, 'coverArt': 'The_Who-Sell_Out.jpg' },	
	{ 'artist': 'The Who', 'title': 'Who\'s Next', 'releaseDate': 1971, 'coverArt': 'The_Who-Whos_Next.jpg' },	
	{ 'artist': 'Traffic', 'title': 'Shoot Out at the Fantasy Factory', 'releaseDate': 1973, 'coverArt': 'Traffic-Shoot_Out_at_the_Fantasy_Factory.jpg' },	
	{ 'artist': 'Various', 'title': 'A Christmas Gift for You from Phil Spector', 'releaseDate': 1963, 'coverArt': 'Various-A_Christmas_Gift_for_You_from_Phil_Spector.jpg' },
	{ 'artist': 'Various', 'title': 'The Guitars That Destroyed the World', 'releaseDate': 1973, 'coverArt': 'Various-Guitars_That_Destroyed_The_World.jpg' },	
	{ 'artist': 'Velvet Underground', 'title': 'Velvet Underground & Nico', 'releaseDate':1967, 'coverArt': 'Velvet_Underground-Velvet_Underground_&_Nico.jpg' },	
	{ 'artist': 'X', 'title': 'Los Angeles', 'releaseDate': 1980, 'coverArt': 'X-Los_Angeles.jpg' },	
	{ 'artist': 'XTC', 'title': 'Drums & Wires', 'releaseDate': 1979, 'coverArt': 'XTC-Drums_&_Wires.jpg' },	
	{ 'artist': 'Yaz', 'title': 'Upstairs at Eric\'s', 'releaseDate': 1982, 'coverArt': 'Yaz-Upstairs_at_Erics.jpg' },	
	{ 'artist': 'Yes', 'title': 'Fragile', 'releaseDate': 1971, 'coverArt': 'Yes-Fragile.jpg' },	
	{ 'artist': 'Yes', 'title': 'Relayer', 'releaseDate': 1974, 'coverArt': 'Yes-Relayer.jpg' },			
	{ 'artist': 'Zombies', 'title': 'Odessey & Oracle', 'releaseDate': 1968, 'coverArt': 'Zombies-Odessey_and_Oracle.jpg' },			
/*	{ 'artist': 'xx', 'title': 'xx', 'releaseDate': 00, 'coverArt': 'xx.jpg' },	
	{ 'artist': 'xx', 'title': 'xx', 'releaseDate': 00, 'coverArt': 'xx.jpg' },	
	{ 'artist': 'xx', 'title': 'xx', 'releaseDate': 00, 'coverArt': 'xx.jpg' },	
	{ 'artist': 'xx', 'title': 'xx', 'releaseDate': 00, 'coverArt': 'xx.jpg' },	 */
];
	